# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-23 17:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_question_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='status',
            field=models.CharField(choices=[(b's', b'Submitted'), (b'a', b'approved'), (b'c', b'Cancel')], max_length=1),
        ),
    ]
