# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-23 17:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20161123_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='status',
            field=models.CharField(choices=[(b'd', b'Draft'), (b'p', b'Published'), (b'w', b'Withdrawn')], max_length=1),
        ),
    ]
