# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-23 17:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20161123_1710'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='status',
        ),
    ]
