# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-23 17:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_remove_question_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='status',
            field=models.CharField(choices=[(b'd', b'Draft'), (b'p', b'Published'), (b'w', b'Withdrawn')], default='d', max_length=1),
            preserve_default=False,
        ),
    ]
